require:
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  Exclude:
    - "bin/**"
    - "db/schema.rb"
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Minitest/LiteralAsActualArgument:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
