FROM ruby:3.3.5-alpine3.20

RUN apk --update add build-base tzdata postgresql-dev postgresql-client

WORKDIR /app
COPY . .

RUN bundle install

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
