default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mc_development
  host: postgres
  password: postgres
  username: postgres

test:
  <<: *default
  database: mc_test
  host: postgres
  password: postgres
  username: postgres

production:
  <<: *default
  database: mc_production
